version: "2"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/test
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
